---

- hosts: compute

  tasks:
    - name: Change the hostname to match *.lilypad.space
      become: yes
      hostname:
        name="{{ inventory_hostname }}"

    - name: Restart node
      become: yes
      command: shutdown -r now "Ansible hostname update"
      async: 0
      poll: 0
      ignore_errors: True
      when:
        reboot is defined

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ inventory_hostname }}" port=22 state=started
    
    #broken
    - name: Validate ansible_hostname == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_hostname == inventory_hostname