---
- name: Install docker on Rocky 8
  hosts: head
  gather_facts: false
  become: true
  tasks:
    - name: Upgrade all packages on servers
      dnf:
        name: '*'
        tags: upgrade
        state: latest

    - name: Uninstall old versions
      dnf:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        tags: remove_old
        state: absent

    - name: Set up docker repository
      tags: add_repo
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: no

    - name: Install the latest version of Docker Engine and containerd
      tags: install_latest
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify: Start and enable docker

    - name: Add the current user to the docker group
      tags: add_user_to_group
      user:
        name: rocky
        groups: docker
        append: yes

  handlers:
    - name: Start and enable docker
      tags: start_service
      systemd:
        name: docker
        state: started